name: IntegrationContinue
on:
  push:
    branches:
    - 'feature/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Tests execution
      run: | 
        docker build --target test-target -t my-calculator-test .
        docker run --rm my-calculator-test
